### ISSUE TITLE
Feature: Sorting of result

### ISSUE THREAD

**Issue by indra4you** [ValEXE-Technologies/Lookup.Spa#3]
Add a sorting option on domain with price result on `WelcomPage` component.

**Sort by**
- Price - Lower to Higher _(ascending)_
- Price - Higher to Lower _(descending)_
- Registrar A-Z _(ascending)_
- Registrar Z-A _(descending)_

**Comment by pajeb4you** [comment]
Implemented "Sort by" feature; [Commit](https://github.com/ValEXE-Technologies/Lookup.Spa/commit/e4b36cde312d6be1c977891cebd48d39850b7753)
